name: AngelCardStats
main: github.saukiya.angelcardstats.AngelCardStats
version: 1.0.0
author: [Saukiya]
softdepend: [PlaceholderAPI,AngelPoints]

commands:
   angelcardstats:
      description: This is a permission command.
      # 命令使用方法，当命令被错误使用时将显示这个
      usage: /<command> test
      aliases: [acs]
permissions:
  angelcardstats.use:
    description: NULL
    default: true
    children:
      angelcardstats.open: true
      angelcardstats.stats: true
      angelcardstats.top: true
  angelcardstats.admin:
    description: NULL
    default: op
    children:
      angelcardstats.save: true
      angelcardstats.info: true
      angelcardstats.give: true
      angelcardstats.reload: true